name: PHP Codeception Tests - develop

on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.*'

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: flex-theme
      use-rest-module: true
      install-composer: true
